name: Publish container image

on:
  push:
    branches:
      - master

jobs:
  publish_to_registry:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run script file
        run: |
         chmod +x ./deploy.sh
         ./deploy.sh ibmcom
        shell: bash